version: "3.9"
services:
  bot_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot_app
    # Говорим, что bot_app зависит от db и redis: запускаем их раньше
    depends_on:
      - db
      - redis
    # Подтягиваем переменные окружения из .env
    env_file:
      - ./.env
    # Порты:
    #  - "8000:8000"  <- Обычно bot_app внутри сети, "наружу" его не пробрасываем,
    #                    т.к. Nginx будет проксировать запросы. Но при отладке
    #                    можно открыть 8000.
    volumes:
      - logs:/app/logs  # Монтируем папку логов
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    depends_on:
      - bot_app
    volumes:
      # Монтируем наш конфиг Nginx в контейнер:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      # Монтируем локальный каталог с сертификатами в контейнер в /etc/nginx/certs
      - ./certs:/etc/nginx/certs:ro

      # Монтируем локальный каталог для логов (./logs) в директорию /var/log/nginx внутри контейнера
      - ./logs:/var/log/nginx

    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

# Объявляем докер-сеть
networks:
  app_network:
    driver: bridge

# Объявляем volume (например, для постоянного хранения данных Postgres и логов)
volumes:
  postgres_data:
  logs:
