version: '3.3'

services:
  bot:
    image: shevka/mtgtgbot:v1.9
    container_name: telegram_bot
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8443:8443"
    networks:
      - bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Ограничение размера лога на 10MB
        max-file: "5"  # До 5 файлов-ротаций

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
