# RDB (снапшоты данных)
save 300 1000  # Сохраняем каждые 5 минут или после 1000 изменений

# AOF (журнал команд)
appendonly yes  # Включаем AOF
appendfsync everysec  # Записываем команды в файл каждую секунду
